language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install pygame==2.0.0.dev6 numpy jaxlib jax tf-nightly matplotlib more-itertools --upgrade
  - git clone https://github.com/DarrenZhang01/TensorFlow_GSoC.git
  - cd TensorFlow_GSoC
  - pip install -e neural-tangents
  - cp tf_jax_stax/*.py tests/
  - cp utils/*.py tests/
  - cp tf_dot_general/tf_dot_general.py tests/

script:
  - python tests/stax_test.py
  # - for f in tests/*.py; do python $f; done
  # - python tf_dot_general/tf_dot_general_test.py
